services:
  postgres:
    build: ./postgres-docker
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    image: hujeremy/springboot-app:latest
    platform: linux/amd64
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/IPRWC-Jeremy
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SECRET_KEY=M7qwTkRMPeuuINz0Az5HX7xRYwV4k0sWyazd8aBAVDU
      - IMAGE_PATH=/app/images

  frontend:
    image: hujeremy/angular-app:latest
    platform: linux/amd64
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8080
